import sys

with open("app/hub/main.gd", "r", encoding="utf-8") as f:
    lines = f.readlines()

new_lines = []
for idx, line in enumerate(lines):
    if idx == 128: # After "panic_style_normal.corner_detail = 1"
        new_lines.append(line)
        new_lines.append('\tpanic_btn.add_theme_stylebox_override("normal", panic_style_normal)\n')
        new_lines.append('\tpanic_btn.add_theme_stylebox_override("hover", style_btn_hover)\n')
        new_lines.append('\tpanic_btn.add_theme_stylebox_override("pressed", style_btn_pressed)\n')
        new_lines.append('\tpanic_btn.add_theme_color_override("font_color", color_ink_white)\n')
        new_lines.append('\tpanic_btn.add_theme_font_size_override("font_size", 14)\n')
        new_lines.append('\t\n')
        new_lines.append('\trestore_btn.add_theme_stylebox_override("normal", style_btn_normal)\n')
        new_lines.append('\trestore_btn.add_theme_stylebox_override("hover", style_btn_hover)\n')
        new_lines.append('\trestore_btn.add_theme_stylebox_override("pressed", style_btn_pressed)\n')
        new_lines.append('\trestore_btn.add_theme_color_override("font_color", color_ink_dim)\n')
        new_lines.append('\trestore_btn.add_theme_font_size_override("font_size", 14)\n')
        new_lines.append('\t\n')
        new_lines.append('\tpanic_btn.pressed.connect(_on_panic_pressed)\n')
        new_lines.append('\trestore_btn.pressed.connect(_on_restore_pressed)\n')
        new_lines.append('\t$UI/TopBar/HelpBtn.pressed.connect(func(): $HelpOverlay.visible = true)\n')
        new_lines.append('\t$HelpOverlay/Panel/Margin/VBox/CloseHelpBtn.pressed.connect(func(): $HelpOverlay.visible = false)\n')
        new_lines.append('\t$UI/Content/SideNav/ScenesBtn.pressed.connect(display_scenes)\n')
        new_lines.append('\t$UI/Content/SideNav/GamesBtn.pressed.connect(display_games)\n')
        new_lines.append('\t$UI/Content/SideNav/LevelsBtn.pressed.connect(_on_levels_nav_pressed)\n')
        new_lines.append('\t$UI/Content/SideNav/CalibrateBtn.pressed.connect(display_calibration_panel)\n')
        new_lines.append('\t$UI/Content/SideNav/DevicesBtn.pressed.connect(display_devices_panel)\n')
        new_lines.append('\t$UI/Content/SideNav/ServiceBtn.pressed.connect(display_service_panel)\n')
        new_lines.append('\t$UI/Content/SideNav/DesignBtn.pressed.connect(_on_design_nav_pressed)\n')
        new_lines.append('\t$UI/Content/SideNav/TestPatternBtn.pressed.connect(_on_test_pattern_pressed)\n')
        new_lines.append('\t\n')
        new_lines.append('\tlauncher.cartridge_exited.connect(_on_cartridge_exited)\n')
        new_lines.append('\tlauncher.ipc_log.connect(log_debug)\n')
        new_lines.append('\t\n')
        new_lines.append('\tsetup_launch_dialog()\n')
        new_lines.append('\tdisplay_scenes()\n')
        new_lines.append('\t\n')
        new_lines.append('\tvar args = OS.get_cmdline_args()\n')
        new_lines.append('\tvar screenshot_mode = ""\n')
        new_lines.append('\tvar screenshot_path = ""\n')
        new_lines.append('\tfor i in range(args.size()):\n')
        new_lines.append('\t\tif args[i] == "--test-screenshot" and i + 1 < args.size():\n')
        new_lines.append('\t\t\tscreenshot_mode = args[i+1]\n')
        new_lines.append('\t\telif args[i] == "--screenshot-path" and i + 1 < args.size():\n')
        new_lines.append('\t\t\tscreenshot_path = args[i+1]\n')
        new_lines.append('\t\t\t\n')
        new_lines.append('\tif screenshot_mode != "" and screenshot_path != "":\n')
        new_lines.append('\t\t_run_auto_screenshot_flow(screenshot_mode, screenshot_path)\n')
        new_lines.append('\t\t\n')
        new_lines.append('\tsetup_splash()\n\n')
        new_lines.append('func setup_splash():\n')
    else:
        new_lines.append(line)

with open("app/hub/main.gd", "w", encoding="utf-8") as f:
    f.writelines(new_lines)
